### ISSUE TITLE
Support the Motorola Beepwear Pro (protocol 6)

### ISSUE THREAD

**Issue by synthead** [synthead/timex_datalink_client#256]
This issue tracks adding protocol 6 support! :tada:

Here's what the software looks like:

![image](https://user-images.githubusercontent.com/820984/213977073-c5a53776-97c4-4e38-8942-9f420916d59c.png)

## Tasks

- [x] #264
- [x] #257
- [x] #258
- [x] https://github.com/synthead/timex_datalink_client/issues/268
- [x] https://github.com/synthead/timex_datalink_client/issues/269
- [x] #259
- [x] https://github.com/synthead/timex_datalink_client/issues/276
- [x] https://github.com/synthead/timex_datalink_client/issues/274
- [x] #260
- [x] #261
- [x] #262
- [x] https://github.com/synthead/timex_datalink_client/issues/263

**Comment by synthead** [comment]
Shipped with v0.12.0! https://github.com/synthead/timex_datalink_client/tree/v0.12.0
